# Generated by Django 2.2.7 on 2019-11-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True)),
                ('data', models.DateTimeField(verbose_name='date published')),
                ('assunto', models.TextField(blank=True)),
                ('pergunta', models.TextField(blank=True)),
                ('resposta', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
