# Generated by Django 2.2.7 on 2019-11-28 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0002_auto_20191128_1736'),
        ('Form', '0002_auto_20191128_2030'),
    ]

    operations = [
    ]
