# Generated by Django 2.2.7 on 2019-11-28 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20191007_1810'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
